### ISSUE TITLE
avant updates

### ISSUE THREAD

**Issue by brettjurgens** [avantcredit/javascript#2]
Put together a quick changelog, let me know what you think...

_17.3-17.5_
use `@FIXME` and `@TODO` instead of `FIXME` & `TODO`

_21.3_
always use `parseInt`

_21.6_
always do `!!`

_22.6_
underscore file names

_23_
use ES6 getters/setters instead

**Comment by brettjurgens** [comment]
@gabelerner @brycedorn @efrankfurt feedback?

**Comment by gabelerner** [comment]
17.3) sure
19.2) i prefer trailing commas for cleaner diffs in all languages, so i'd keep their suggestion
21.3) sure
21.6) sure
22.6) sure
23) sure

**Comment by brettjurgens** [comment]
19.2 agreed with cleaner diffs, didn't realize it was part of ES5, so we can keep

**Comment by brycedorn** [comment]
why `parseInt()` over `Number()`? I get that it parses instead of type conversion but leading 0's messes it up:

``` js
Number("010");     // 10
parseInt("010");   // 8, implicit octal
```

everything else +1

**Comment by brettjurgens** [comment]
`Number()` is a constructor and `parseInt` is a function to parse integers. leading zeros is not a problem IMO.

according to JSPerf, `parseInt` gives consistently better performance.

**Comment by brycedorn** [comment]
IMO might be helpful to make a tl;dr with most important bits in avant's wiki (and then link to this), since we definitely need a comprehensive styleguide like this but for people who don't write javascript often a lot of this won't be relevant.

**Comment by brettjurgens** [comment]
it's all important :smile:

I think the table of contents should be comprehensive enough, though
